service: thenotetaker

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  list:
    handler: bin/list
    events:
      - http:
          path: /list
          method: get

resources:
  Resources:
    NotesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: timestamp
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: notes
